arraylist.o:
	$(CC) $(PORT_INCLUDE) $(CFLAGS) -c arraylist.c
	$(CC) $(PORT_INCLUDE) $(CFLAGS) -c debug.c
	$(CC) $(PORT_INCLUDE) $(CFLAGS) -c json_object.c
	$(CC) $(PORT_INCLUDE) $(CFLAGS) -c json_tokener.c
	$(CC) $(PORT_INCLUDE) $(CFLAGS) -c json_util.c
	$(CC) $(PORT_INCLUDE) $(CFLAGS) -c linkhash.c
	$(CC) $(PORT_INCLUDE) $(CFLAGS) -c printbuf.c
	$(CC) $(PORT_INCLUDE) $(CFLAGS) -c json_object_iterator.c
	$(CC) $(PORT_INCLUDE) $(CFLAGS) -c json_c_version.c

clean:
	rm -f *.o