/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_terragoedge_geopkg_read_GeoPackageRasterReader */

#ifndef _Included_com_terragoedge_geopkg_read_GeoPackageRasterReader
#define _Included_com_terragoedge_geopkg_read_GeoPackageRasterReader
#ifdef __cplusplus
extern "C" {
#endif
/*
JNIEXPORT jlong JNICALL Java_com_terragoedge_geopkg_read_GeoPackageRasterReader_setGDALDATA
        (JNIEnv *, jobject, jlong, jstring);*/
/*
 * Class:     com_terragoedge_geopkg_read_GeoPackageRasterReader
 * Method:    createGeoPackageRasterReader
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_terragoedge_geopkg_read_GeoPackageRasterReader_createGeoPackageRasterReader
  (JNIEnv *, jobject);

/*
 * Class:     com_terragoedge_geopkg_read_GeoPackageRasterReader
 * Method:    openGeoPackage
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_terragoedge_geopkg_read_GeoPackageRasterReader_openGeoPackage
  (JNIEnv *, jobject, jlong, jstring, jstring);

JNIEXPORT jint JNICALL Java_com_terragoedge_geopkg_read_GeoPackageRasterReader_convertGeoPackage
        (JNIEnv *, jobject , jlong , jstring, jstring , jstring, jstring );

/*
 * Class:     com_terragoedge_geopkg_read_GeoPackageRasterReader
 * Method:    getGeoPackageRasterNameListAsJSON
 * Signature: (J)I
 */
JNIEXPORT jstring JNICALL Java_com_terragoedge_geopkg_read_GeoPackageRasterReader_getGeoPackageRasterNameListAsJSON
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_terragoedge_geopkg_read_GeoPackageRasterReader
 * Method:    initiateGeoPackageToMBTilesConversion
 * Signature: (JLjava/lang/String;IIIILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_terragoedge_geopkg_read_GeoPackageRasterReader_initiateGeoPackageToMBTilesConversion
  (JNIEnv *, jobject, jlong, jstring, jint, jint, jint, jint, jstring);

/*
 * Class:     com_terragoedge_geopkg_read_GeoPackageRasterReader
 * Method:    cancelGeoPackageToMBTilesConversion
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_terragoedge_geopkg_read_GeoPackageRasterReader_cancelGeoPackageToMBTilesConversion
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_terragoedge_geopkg_read_GeoPackageRasterReader
 * Method:    getGeoPackageToMBTileConversionStatus
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_terragoedge_geopkg_read_GeoPackageRasterReader_getGeoPackageToMBTileConversionStatus
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_terragoedge_geopkg_read_GeoPackageRasterReader
 * Method:    getGeoPackageRasterReaderState
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_terragoedge_geopkg_read_GeoPackageRasterReader_getGeoPackageRasterReaderState
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_terragoedge_geopkg_read_GeoPackageRasterReader
 * Method:    closeGeoPackage
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_terragoedge_geopkg_read_GeoPackageRasterReader_closeGeoPackage
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_terragoedge_geopkg_read_GeoPackageRasterReader
 * Method:    destroyGeoPackageRasterReader
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_terragoedge_geopkg_read_GeoPackageRasterReader_destroyGeoPackageRasterReader
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
