# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := fx_lpng
DEFS_Debug := \
	'-DPNG_PREFIX' \
	'-DPNGPREFIX_H' \
	'-DPNG_USE_READ_MACROS' \
	'-DV8_DEPRECATION_WARNINGS'

# Flags passed to all source files.
CFLAGS_Debug := \
	-Wall \
	-W \
	-Wno-missing-field-initializers \
	-Wno-sign-compare \
	-Wno-unused-parameter \
	-pthread \
	-fno-exceptions \
	-fPIC \
	-g \
	-O0 \
	-fdata-sections \
	-ffunction-sections

# Flags passed to only C files.
CFLAGS_C_Debug :=

# Flags passed to only C++ files.
CFLAGS_CC_Debug := \
	-std=c++0x \
	-Wnon-virtual-dtor \
	-fno-rtti

INCS_Debug := \
	-I. \
	-Icore/src/fxcodec/fx_zlib/include

DEFS_Debug_x64 := \
	'-DPNG_PREFIX' \
	'-DPNGPREFIX_H' \
	'-DPNG_USE_READ_MACROS' \
	'-DV8_DEPRECATION_WARNINGS'

# Flags passed to all source files.
CFLAGS_Debug_x64 := \
	-Wall \
	-W \
	-Wno-missing-field-initializers \
	-Wno-sign-compare \
	-Wno-unused-parameter \
	-pthread \
	-fno-exceptions \
	-fPIC \
	-g \
	-O0 \
	-fdata-sections \
	-ffunction-sections

# Flags passed to only C files.
CFLAGS_C_Debug_x64 :=

# Flags passed to only C++ files.
CFLAGS_CC_Debug_x64 := \
	-std=c++0x \
	-Wnon-virtual-dtor \
	-fno-rtti

INCS_Debug_x64 := \
	-I. \
	-Icore/src/fxcodec/fx_zlib/include

DEFS_Release := \
	'-DPNG_PREFIX' \
	'-DPNGPREFIX_H' \
	'-DPNG_USE_READ_MACROS' \
	'-DV8_DEPRECATION_WARNINGS'

# Flags passed to all source files.
CFLAGS_Release := \
	-Wall \
	-W \
	-Wno-missing-field-initializers \
	-Wno-sign-compare \
	-Wno-unused-parameter \
	-pthread \
	-fno-exceptions \
	-fPIC \
	-fno-strict-aliasing \
	-fdata-sections \
	-ffunction-sections \
	-O3 \
	-O2

# Flags passed to only C files.
CFLAGS_C_Release :=

# Flags passed to only C++ files.
CFLAGS_CC_Release := \
	-std=c++0x \
	-Wnon-virtual-dtor \
	-fno-rtti

INCS_Release := \
	-I. \
	-Icore/src/fxcodec/fx_zlib/include

DEFS_Release_x64 := \
	'-DPNG_PREFIX' \
	'-DPNGPREFIX_H' \
	'-DPNG_USE_READ_MACROS' \
	'-DV8_DEPRECATION_WARNINGS'

# Flags passed to all source files.
CFLAGS_Release_x64 := \
	-Wall \
	-W \
	-Wno-missing-field-initializers \
	-Wno-sign-compare \
	-Wno-unused-parameter \
	-pthread \
	-fno-exceptions \
	-fPIC \
	-fno-strict-aliasing \
	-fdata-sections \
	-ffunction-sections \
	-O3 \
	-O2

# Flags passed to only C files.
CFLAGS_C_Release_x64 :=

# Flags passed to only C++ files.
CFLAGS_CC_Release_x64 := \
	-std=c++0x \
	-Wnon-virtual-dtor \
	-fno-rtti

INCS_Release_x64 := \
	-I. \
	-Icore/src/fxcodec/fx_zlib/include

OBJS := \
	$(obj).target/$(TARGET)/samples/fx_lpng/src/fx_png.o \
	$(obj).target/$(TARGET)/samples/fx_lpng/src/fx_pngerror.o \
	$(obj).target/$(TARGET)/samples/fx_lpng/src/fx_pngget.o \
	$(obj).target/$(TARGET)/samples/fx_lpng/src/fx_pngmem.o \
	$(obj).target/$(TARGET)/samples/fx_lpng/src/fx_pngpread.o \
	$(obj).target/$(TARGET)/samples/fx_lpng/src/fx_pngread.o \
	$(obj).target/$(TARGET)/samples/fx_lpng/src/fx_pngrio.o \
	$(obj).target/$(TARGET)/samples/fx_lpng/src/fx_pngrtran.o \
	$(obj).target/$(TARGET)/samples/fx_lpng/src/fx_pngrutil.o \
	$(obj).target/$(TARGET)/samples/fx_lpng/src/fx_pngset.o \
	$(obj).target/$(TARGET)/samples/fx_lpng/src/fx_pngtrans.o \
	$(obj).target/$(TARGET)/samples/fx_lpng/src/fx_pngwio.o \
	$(obj).target/$(TARGET)/samples/fx_lpng/src/fx_pngwrite.o \
	$(obj).target/$(TARGET)/samples/fx_lpng/src/fx_pngwtran.o \
	$(obj).target/$(TARGET)/samples/fx_lpng/src/fx_pngwutil.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := \
	-pthread

LDFLAGS_Debug_x64 := \
	-pthread

LDFLAGS_Release := \
	-pthread

LDFLAGS_Release_x64 := \
	-pthread

LIBS :=

$(obj).target/samples/libfx_lpng.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/samples/libfx_lpng.a: LIBS := $(LIBS)
$(obj).target/samples/libfx_lpng.a: TOOLSET := $(TOOLSET)
$(obj).target/samples/libfx_lpng.a: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,alink_thin)

all_deps += $(obj).target/samples/libfx_lpng.a
# Add target alias
.PHONY: fx_lpng
fx_lpng: $(obj).target/samples/libfx_lpng.a

# Add target alias to "all" target.
.PHONY: all
all: fx_lpng

