ogrmemdriver.o:
	$(CXX) $(PORT_INCLUDE) $(APPS_INCLUDE) $(CORE_INCLUDE) $(OGR_INCLUDE) $(OGR_INCLUDE)/ogrsf_frmts $(CXXFLAGS) -c ogrmemdriver.cpp
	$(CXX) $(PORT_INCLUDE) $(APPS_INCLUDE) $(CORE_INCLUDE) $(OGR_INCLUDE) $(OGR_INCLUDE)/ogrsf_frmts $(CXXFLAGS) -c ogrmemdatasource.cpp
	$(CXX) $(PORT_INCLUDE) $(APPS_INCLUDE) $(CORE_INCLUDE) $(OGR_INCLUDE) $(OGR_INCLUDE)/ogrsf_frmts $(CXXFLAGS) -c ogrmemlayer.cpp

clean:
	rm -f *.o


