ogrgeojsondriver.o:
	$(CXX) $(APPS_INCLUDE) $(OGR_INCLUDE)/ogrsf_frmts/geojson/libjson $(CORE_INCLUDE) $(OGR_INCLUDE) $(OGR_INCLUDE)/ogrsf_frmts $(PORT_INCLUDE) $(CXXFLAGS) -c ogrgeojsondriver.cpp
	$(CXX) $(APPS_INCLUDE) $(OGR_INCLUDE)/ogrsf_frmts/geojson/libjson $(CORE_INCLUDE) $(OGR_INCLUDE) $(OGR_INCLUDE)/ogrsf_frmts $(PORT_INCLUDE) $(CXXFLAGS) -c ogrgeojsondatasource.cpp
	$(CXX) $(APPS_INCLUDE) $(OGR_INCLUDE)/ogrsf_frmts/geojson/libjson $(CORE_INCLUDE) $(OGR_INCLUDE) $(OGR_INCLUDE)/ogrsf_frmts $(PORT_INCLUDE) $(CXXFLAGS) -c ogrgeojsonlayer.cpp
	$(CXX) $(APPS_INCLUDE) $(OGR_INCLUDE)/ogrsf_frmts/geojson/libjson $(CORE_INCLUDE) $(OGR_INCLUDE) $(OGR_INCLUDE)/ogrsf_frmts $(PORT_INCLUDE) $(CXXFLAGS) -c ogrgeojsonwritelayer.cpp
	$(CXX) $(APPS_INCLUDE) $(OGR_INCLUDE)/ogrsf_frmts/geojson/libjson $(CORE_INCLUDE) $(OGR_INCLUDE) $(OGR_INCLUDE)/ogrsf_frmts $(PORT_INCLUDE) $(CXXFLAGS) -c ogrgeojsonutils.cpp
	$(CXX) $(APPS_INCLUDE) $(OGR_INCLUDE)/ogrsf_frmts/geojson/libjson $(CORE_INCLUDE) $(OGR_INCLUDE) $(OGR_INCLUDE)/ogrsf_frmts $(PORT_INCLUDE) $(CXXFLAGS) -c ogrgeojsonreader.cpp
	$(CXX) $(APPS_INCLUDE) $(OGR_INCLUDE)/ogrsf_frmts/geojson/libjson $(CORE_INCLUDE) $(OGR_INCLUDE) $(OGR_INCLUDE)/ogrsf_frmts $(PORT_INCLUDE) $(CXXFLAGS) -c ogrgeojsonwriter.cpp
	$(CXX) $(APPS_INCLUDE) $(OGR_INCLUDE)/ogrsf_frmts/geojson/libjson $(CORE_INCLUDE) $(OGR_INCLUDE) $(OGR_INCLUDE)/ogrsf_frmts $(PORT_INCLUDE) $(CXXFLAGS) -c ogresrijsonreader.cpp
	$(CXX) $(APPS_INCLUDE) $(OGR_INCLUDE)/ogrsf_frmts/geojson/libjson $(CORE_INCLUDE) $(OGR_INCLUDE) $(OGR_INCLUDE)/ogrsf_frmts $(PORT_INCLUDE) $(CXXFLAGS) -c ogrtopojsonreader.cpp

clean: 
	rm -f *.o