ogrxplanedriver.o:
		$(CXX) $(CORE_INCLUDE) $(OGR_INCLUDE) $(PORT_INCLUDE) $(OGR_INCLUDE)/ogrsf_frmts $(CXXFLAGS) -c ogrxplanedriver.cpp
		$(CXX) $(CORE_INCLUDE) $(OGR_INCLUDE) $(PORT_INCLUDE) $(OGR_INCLUDE)/ogrsf_frmts $(CXXFLAGS) -c ogrxplanedatasource.cpp
		$(CXX) $(CORE_INCLUDE) $(OGR_INCLUDE) $(PORT_INCLUDE) $(OGR_INCLUDE)/ogrsf_frmts $(CXXFLAGS) -c ogrxplanelayer.cpp
		$(CXX) $(CORE_INCLUDE) $(OGR_INCLUDE) $(PORT_INCLUDE) $(OGR_INCLUDE)/ogrsf_frmts $(CXXFLAGS) -c ogr_xplane_geo_utils.cpp
		$(CXX) $(CORE_INCLUDE) $(OGR_INCLUDE) $(PORT_INCLUDE) $(OGR_INCLUDE)/ogrsf_frmts $(CXXFLAGS) -c ogr_xplane_reader.cpp
		$(CXX) $(CORE_INCLUDE) $(OGR_INCLUDE) $(PORT_INCLUDE) $(OGR_INCLUDE)/ogrsf_frmts $(CXXFLAGS) -c ogr_xplane_apt_reader.cpp
		$(CXX) $(CORE_INCLUDE) $(OGR_INCLUDE) $(PORT_INCLUDE) $(OGR_INCLUDE)/ogrsf_frmts $(CXXFLAGS) -c ogr_xplane_nav_reader.cpp
		$(CXX) $(CORE_INCLUDE) $(OGR_INCLUDE) $(PORT_INCLUDE) $(OGR_INCLUDE)/ogrsf_frmts $(CXXFLAGS) -c ogr_xplane_fix_reader.cpp
		$(CXX) $(CORE_INCLUDE) $(OGR_INCLUDE) $(PORT_INCLUDE) $(OGR_INCLUDE)/ogrsf_frmts $(CXXFLAGS) -c ogr_xplane_awy_reader.cpp

clean:
	rm -f *.o