# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := fpdfapi
DEFS_Debug := \
	'-DOPJ_STATIC' \
	'-DV8_DEPRECATION_WARNINGS' \
	'-D_CRT_SECURE_NO_WARNINGS' \
	'-D_FX_CPU_=_FX_X64_'

# Flags passed to all source files.
CFLAGS_Debug := \
	-Wall \
	-W \
	-Wno-missing-field-initializers \
	-Wno-sign-compare \
	-Wno-unused-parameter \
	-pthread \
	-fno-exceptions \
	-fPIC \
	-fPIC \
	-g \
	-O0 \
	-fdata-sections \
	-ffunction-sections

# Flags passed to only C files.
CFLAGS_C_Debug :=

# Flags passed to only C++ files.
CFLAGS_CC_Debug := \
	-std=c++0x \
	-Wnon-virtual-dtor \
	-fno-rtti

INCS_Debug := \
	-Ithird_party/freetype/include

DEFS_Debug_x64 := \
	'-DOPJ_STATIC' \
	'-DV8_DEPRECATION_WARNINGS' \
	'-D_CRT_SECURE_NO_WARNINGS' \
	'-D_FX_CPU_=_FX_X64_'

# Flags passed to all source files.
CFLAGS_Debug_x64 := \
	-Wall \
	-W \
	-Wno-missing-field-initializers \
	-Wno-sign-compare \
	-Wno-unused-parameter \
	-pthread \
	-fno-exceptions \
	-fPIC \
	-fPIC \
	-g \
	-O0 \
	-fdata-sections \
	-ffunction-sections

# Flags passed to only C files.
CFLAGS_C_Debug_x64 :=

# Flags passed to only C++ files.
CFLAGS_CC_Debug_x64 := \
	-std=c++0x \
	-Wnon-virtual-dtor \
	-fno-rtti

INCS_Debug_x64 := \
	-Ithird_party/freetype/include

DEFS_Release := \
	'-DOPJ_STATIC' \
	'-DV8_DEPRECATION_WARNINGS' \
	'-D_CRT_SECURE_NO_WARNINGS' \
	'-D_FX_CPU_=_FX_X64_'

# Flags passed to all source files.
CFLAGS_Release := \
	-Wall \
	-W \
	-Wno-missing-field-initializers \
	-Wno-sign-compare \
	-Wno-unused-parameter \
	-pthread \
	-fno-exceptions \
	-fPIC \
	-fPIC \
	-fno-strict-aliasing \
	-fdata-sections \
	-ffunction-sections \
	-O3 \
	-O2

# Flags passed to only C files.
CFLAGS_C_Release :=

# Flags passed to only C++ files.
CFLAGS_CC_Release := \
	-std=c++0x \
	-Wnon-virtual-dtor \
	-fno-rtti

INCS_Release := \
	-Ithird_party/freetype/include

DEFS_Release_x64 := \
	'-DOPJ_STATIC' \
	'-DV8_DEPRECATION_WARNINGS' \
	'-D_CRT_SECURE_NO_WARNINGS' \
	'-D_FX_CPU_=_FX_X64_'

# Flags passed to all source files.
CFLAGS_Release_x64 := \
	-Wall \
	-W \
	-Wno-missing-field-initializers \
	-Wno-sign-compare \
	-Wno-unused-parameter \
	-pthread \
	-fno-exceptions \
	-fPIC \
	-fPIC \
	-fno-strict-aliasing \
	-fdata-sections \
	-ffunction-sections \
	-O3 \
	-O2

# Flags passed to only C files.
CFLAGS_C_Release_x64 :=

# Flags passed to only C++ files.
CFLAGS_CC_Release_x64 := \
	-std=c++0x \
	-Wnon-virtual-dtor \
	-fno-rtti

INCS_Release_x64 := \
	-Ithird_party/freetype/include

OBJS := \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_basic_module.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/CNS1/Adobe-CNS1-UCS2_5.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/CNS1/B5pc-H_0.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/CNS1/B5pc-V_0.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/CNS1/cmaps_cns1.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/CNS1/CNS-EUC-H_0.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/CNS1/CNS-EUC-V_0.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/CNS1/ETen-B5-H_0.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/CNS1/ETen-B5-V_0.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/CNS1/ETenms-B5-H_0.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/CNS1/ETenms-B5-V_0.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/CNS1/HKscs-B5-H_5.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/CNS1/HKscs-B5-V_5.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/CNS1/UniCNS-UCS2-H_3.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/CNS1/UniCNS-UCS2-V_3.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/CNS1/UniCNS-UTF16-H_0.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/fpdf_cmaps.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/GB1/Adobe-GB1-UCS2_5.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/GB1/cmaps_gb1.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/GB1/GB-EUC-H_0.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/GB1/GB-EUC-V_0.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/GB1/GBK-EUC-H_2.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/GB1/GBK-EUC-V_2.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/GB1/GBK2K-H_5.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/GB1/GBK2K-V_5.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/GB1/GBKp-EUC-H_2.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/GB1/GBKp-EUC-V_2.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/GB1/GBpc-EUC-H_0.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/GB1/GBpc-EUC-V_0.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/GB1/UniGB-UCS2-H_4.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/GB1/UniGB-UCS2-V_4.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/Japan1/83pv-RKSJ-H_1.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/Japan1/90ms-RKSJ-H_2.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/Japan1/90ms-RKSJ-V_2.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/Japan1/90msp-RKSJ-H_2.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/Japan1/90msp-RKSJ-V_2.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/Japan1/90pv-RKSJ-H_1.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/Japan1/Add-RKSJ-H_1.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/Japan1/Add-RKSJ-V_1.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/Japan1/Adobe-Japan1-UCS2_4.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/Japan1/cmaps_japan1.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/Japan1/EUC-H_1.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/Japan1/EUC-V_1.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/Japan1/Ext-RKSJ-H_2.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/Japan1/Ext-RKSJ-V_2.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/Japan1/H_1.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/Japan1/UniJIS-UCS2-HW-H_4.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/Japan1/UniJIS-UCS2-HW-V_4.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/Japan1/UniJIS-UCS2-H_4.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/Japan1/UniJIS-UCS2-V_4.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/Japan1/UniJIS-UTF16-H_5.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/Japan1/UniJIS-UTF16-V_5.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/Japan1/V_1.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/Korea1/Adobe-Korea1-UCS2_2.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/Korea1/cmaps_korea1.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/Korea1/KSC-EUC-H_0.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/Korea1/KSC-EUC-V_0.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/Korea1/KSCms-UHC-HW-H_1.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/Korea1/KSCms-UHC-HW-V_1.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/Korea1/KSCms-UHC-H_1.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/Korea1/KSCms-UHC-V_1.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/Korea1/KSCpc-EUC-H_0.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/Korea1/UniKS-UCS2-H_1.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/Korea1/UniKS-UCS2-V_1.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_cmaps/Korea1/UniKS-UTF16-H_0.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_edit/fpdf_edit_content.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_edit/fpdf_edit_create.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_edit/fpdf_edit_doc.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_edit/fpdf_edit_image.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_font/fpdf_font.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_font/fpdf_font_charset.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_font/fpdf_font_cid.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_font/ttgsubtable.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_page/fpdf_page.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_page/fpdf_page_colors.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_page/fpdf_page_doc.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_page/fpdf_page_func.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_page/fpdf_page_graph_state.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_page/fpdf_page_image.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_page/fpdf_page_parser.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_page/fpdf_page_parser_old.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_page/fpdf_page_path.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_page/fpdf_page_pattern.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_parser/fpdf_parser_decode.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_parser/fpdf_parser_document.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_parser/fpdf_parser_encrypt.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_parser/fpdf_parser_fdf.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_parser/fpdf_parser_filters.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_parser/fpdf_parser_objects.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_parser/fpdf_parser_parser.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_parser/fpdf_parser_utility.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_render/fpdf_render.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_render/fpdf_render_cache.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_render/fpdf_render_image.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_render/fpdf_render_loadimage.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_render/fpdf_render_pattern.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_render/fpdf_render_text.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := \
	-pthread \
	-L$(builddir)

LDFLAGS_Debug_x64 := \
	-pthread \
	-L$(builddir)

LDFLAGS_Release := \
	-pthread \
	-L$(builddir)

LDFLAGS_Release_x64 := \
	-pthread \
	-L$(builddir)

LIBS :=

$(obj).target/libfpdfapi.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/libfpdfapi.a: LIBS := $(LIBS)
$(obj).target/libfpdfapi.a: TOOLSET := $(TOOLSET)
$(obj).target/libfpdfapi.a: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,alink_thin)

all_deps += $(obj).target/libfpdfapi.a
# Add target alias
.PHONY: fpdfapi
fpdfapi: $(obj).target/libfpdfapi.a

# Add target alias to "all" target.
.PHONY: all
all: fpdfapi

