# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := pdfium_embeddertests
DEFS_Debug := \
	'-DOPJ_STATIC' \
	'-DV8_DEPRECATION_WARNINGS' \
	'-D_CRT_SECURE_NO_WARNINGS' \
	'-D_FX_CPU_=_FX_X64_' \
	'-DGTEST_HAS_POSIX_RE=0' \
	'-DGTEST_LANG_CXX11=0' \
	'-DUNIT_TEST' \
	'-DGTEST_HAS_RTTI=0'

# Flags passed to all source files.
CFLAGS_Debug := \
	-Wall \
	-W \
	-Wno-missing-field-initializers \
	-Wno-sign-compare \
	-Wno-unused-parameter \
	-pthread \
	-fno-exceptions \
	-fPIC \
	-fPIC \
	-g \
	-O0 \
	-fdata-sections \
	-ffunction-sections

# Flags passed to only C files.
CFLAGS_C_Debug :=

# Flags passed to only C++ files.
CFLAGS_CC_Debug := \
	-std=c++0x \
	-Wnon-virtual-dtor \
	-fno-rtti

INCS_Debug := \
	-Ithird_party/freetype/include \
	-I. \
	-Itesting/gmock/include \
	-Itesting/gtest/include

DEFS_Debug_x64 := \
	'-DOPJ_STATIC' \
	'-DV8_DEPRECATION_WARNINGS' \
	'-D_CRT_SECURE_NO_WARNINGS' \
	'-D_FX_CPU_=_FX_X64_' \
	'-DGTEST_HAS_POSIX_RE=0' \
	'-DGTEST_LANG_CXX11=0' \
	'-DUNIT_TEST' \
	'-DGTEST_HAS_RTTI=0'

# Flags passed to all source files.
CFLAGS_Debug_x64 := \
	-Wall \
	-W \
	-Wno-missing-field-initializers \
	-Wno-sign-compare \
	-Wno-unused-parameter \
	-pthread \
	-fno-exceptions \
	-fPIC \
	-fPIC \
	-g \
	-O0 \
	-fdata-sections \
	-ffunction-sections

# Flags passed to only C files.
CFLAGS_C_Debug_x64 :=

# Flags passed to only C++ files.
CFLAGS_CC_Debug_x64 := \
	-std=c++0x \
	-Wnon-virtual-dtor \
	-fno-rtti

INCS_Debug_x64 := \
	-Ithird_party/freetype/include \
	-I. \
	-Itesting/gmock/include \
	-Itesting/gtest/include

DEFS_Release := \
	'-DOPJ_STATIC' \
	'-DV8_DEPRECATION_WARNINGS' \
	'-D_CRT_SECURE_NO_WARNINGS' \
	'-D_FX_CPU_=_FX_X64_' \
	'-DGTEST_HAS_POSIX_RE=0' \
	'-DGTEST_LANG_CXX11=0' \
	'-DUNIT_TEST' \
	'-DGTEST_HAS_RTTI=0'

# Flags passed to all source files.
CFLAGS_Release := \
	-Wall \
	-W \
	-Wno-missing-field-initializers \
	-Wno-sign-compare \
	-Wno-unused-parameter \
	-pthread \
	-fno-exceptions \
	-fPIC \
	-fPIC \
	-fno-strict-aliasing \
	-fdata-sections \
	-ffunction-sections \
	-O3 \
	-O2

# Flags passed to only C files.
CFLAGS_C_Release :=

# Flags passed to only C++ files.
CFLAGS_CC_Release := \
	-std=c++0x \
	-Wnon-virtual-dtor \
	-fno-rtti

INCS_Release := \
	-Ithird_party/freetype/include \
	-I. \
	-Itesting/gmock/include \
	-Itesting/gtest/include

DEFS_Release_x64 := \
	'-DOPJ_STATIC' \
	'-DV8_DEPRECATION_WARNINGS' \
	'-D_CRT_SECURE_NO_WARNINGS' \
	'-D_FX_CPU_=_FX_X64_' \
	'-DGTEST_HAS_POSIX_RE=0' \
	'-DGTEST_LANG_CXX11=0' \
	'-DUNIT_TEST' \
	'-DGTEST_HAS_RTTI=0'

# Flags passed to all source files.
CFLAGS_Release_x64 := \
	-Wall \
	-W \
	-Wno-missing-field-initializers \
	-Wno-sign-compare \
	-Wno-unused-parameter \
	-pthread \
	-fno-exceptions \
	-fPIC \
	-fPIC \
	-fno-strict-aliasing \
	-fdata-sections \
	-ffunction-sections \
	-O3 \
	-O2

# Flags passed to only C files.
CFLAGS_C_Release_x64 :=

# Flags passed to only C++ files.
CFLAGS_CC_Release_x64 := \
	-std=c++0x \
	-Wnon-virtual-dtor \
	-fno-rtti

INCS_Release_x64 := \
	-Ithird_party/freetype/include \
	-I. \
	-Itesting/gmock/include \
	-Itesting/gtest/include

OBJS := \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_parser/fpdf_parser_decode_embeddertest.o \
	$(obj).target/$(TARGET)/core/src/fpdfapi/fpdf_parser/fpdf_parser_parser_embeddertest.o \
	$(obj).target/$(TARGET)/fpdfsdk/src/fpdf_dataavail_embeddertest.o \
	$(obj).target/$(TARGET)/fpdfsdk/src/fpdfdoc_embeddertest.o \
	$(obj).target/$(TARGET)/fpdfsdk/src/fpdfformfill_embeddertest.o \
	$(obj).target/$(TARGET)/fpdfsdk/src/fpdftext_embeddertest.o \
	$(obj).target/$(TARGET)/fpdfsdk/src/fpdfview_c_api_test.o \
	$(obj).target/$(TARGET)/fpdfsdk/src/fpdfview_embeddertest.o \
	$(obj).target/$(TARGET)/testing/embedder_test.o \
	$(obj).target/$(TARGET)/testing/fx_string_testhelpers.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# Make sure our dependencies are built before any of us.
$(OBJS): | $(obj).target/testing/libgmock.a $(obj).target/testing/libgtest.a $(obj).target/libpdfium.a $(obj).target/testing/gtest_prod.stamp $(obj).target/third_party/libbigint.a $(obj).target/third_party/pdfium_base.stamp $(obj).target/libfpdfapi.a $(obj).target/libfdrm.a $(obj).target/libfpdfdoc.a $(obj).target/libfpdftext.a $(obj).target/libformfiller.a $(obj).target/libfxcodec.a $(obj).target/third_party/libfx_lcms2.a $(obj).target/third_party/libfx_libjpeg.a $(obj).target/third_party/libfx_libopenjpeg.a $(obj).target/third_party/libfx_zlib.a $(obj).target/libfxcrt.a $(obj).target/libfxedit.a $(obj).target/libfxge.a $(obj).target/third_party/libfx_agg.a $(obj).target/libpdfwindow.a $(obj).target/third_party/libfreetype.a

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := \
	-pthread

LDFLAGS_Debug_x64 := \
	-pthread

LDFLAGS_Release := \
	-pthread

LDFLAGS_Release_x64 := \
	-pthread

LIBS := \
	-lfpdfapi

$(builddir)/pdfium_embeddertests: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(builddir)/pdfium_embeddertests: LIBS := $(LIBS)
$(builddir)/pdfium_embeddertests: LD_INPUTS := $(OBJS) $(obj).target/testing/libgmock.a $(obj).target/testing/libgtest.a $(obj).target/libpdfium.a $(obj).target/third_party/libbigint.a $(obj).target/libfpdfapi.a $(obj).target/libfdrm.a $(obj).target/libfpdfdoc.a $(obj).target/libfpdftext.a $(obj).target/libformfiller.a $(obj).target/libfxcodec.a $(obj).target/third_party/libfx_lcms2.a $(obj).target/third_party/libfx_libjpeg.a $(obj).target/third_party/libfx_libopenjpeg.a $(obj).target/third_party/libfx_zlib.a $(obj).target/libfxcrt.a $(obj).target/libfxedit.a $(obj).target/libfxge.a $(obj).target/third_party/libfx_agg.a $(obj).target/libpdfwindow.a $(obj).target/third_party/libfreetype.a
$(builddir)/pdfium_embeddertests: TOOLSET := $(TOOLSET)
$(builddir)/pdfium_embeddertests: $(OBJS) $(obj).target/testing/libgmock.a $(obj).target/testing/libgtest.a $(obj).target/libpdfium.a $(obj).target/third_party/libbigint.a $(obj).target/libfpdfapi.a $(obj).target/libfdrm.a $(obj).target/libfpdfdoc.a $(obj).target/libfpdftext.a $(obj).target/libformfiller.a $(obj).target/libfxcodec.a $(obj).target/third_party/libfx_lcms2.a $(obj).target/third_party/libfx_libjpeg.a $(obj).target/third_party/libfx_libopenjpeg.a $(obj).target/third_party/libfx_zlib.a $(obj).target/libfxcrt.a $(obj).target/libfxedit.a $(obj).target/libfxge.a $(obj).target/third_party/libfx_agg.a $(obj).target/libpdfwindow.a $(obj).target/third_party/libfreetype.a FORCE_DO_CMD
	$(call do_cmd,link)

all_deps += $(builddir)/pdfium_embeddertests
# Add target alias
.PHONY: pdfium_embeddertests
pdfium_embeddertests: $(builddir)/pdfium_embeddertests

# Add executable to "all" target.
.PHONY: all
all: $(builddir)/pdfium_embeddertests

