# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := pdfwindow
DEFS_Debug := \
	'-DOPJ_STATIC' \
	'-DV8_DEPRECATION_WARNINGS' \
	'-D_CRT_SECURE_NO_WARNINGS' \
	'-D_FX_CPU_=_FX_X64_'

# Flags passed to all source files.
CFLAGS_Debug := \
	-Wall \
	-W \
	-Wno-missing-field-initializers \
	-Wno-sign-compare \
	-Wno-unused-parameter \
	-pthread \
	-fno-exceptions \
	-fPIC \
	-fPIC \
	-g \
	-O0 \
	-fdata-sections \
	-ffunction-sections

# Flags passed to only C files.
CFLAGS_C_Debug :=

# Flags passed to only C++ files.
CFLAGS_CC_Debug := \
	-std=c++0x \
	-Wnon-virtual-dtor \
	-fno-rtti

INCS_Debug := \
	-Ithird_party/freetype/include

DEFS_Debug_x64 := \
	'-DOPJ_STATIC' \
	'-DV8_DEPRECATION_WARNINGS' \
	'-D_CRT_SECURE_NO_WARNINGS' \
	'-D_FX_CPU_=_FX_X64_'

# Flags passed to all source files.
CFLAGS_Debug_x64 := \
	-Wall \
	-W \
	-Wno-missing-field-initializers \
	-Wno-sign-compare \
	-Wno-unused-parameter \
	-pthread \
	-fno-exceptions \
	-fPIC \
	-fPIC \
	-g \
	-O0 \
	-fdata-sections \
	-ffunction-sections

# Flags passed to only C files.
CFLAGS_C_Debug_x64 :=

# Flags passed to only C++ files.
CFLAGS_CC_Debug_x64 := \
	-std=c++0x \
	-Wnon-virtual-dtor \
	-fno-rtti

INCS_Debug_x64 := \
	-Ithird_party/freetype/include

DEFS_Release := \
	'-DOPJ_STATIC' \
	'-DV8_DEPRECATION_WARNINGS' \
	'-D_CRT_SECURE_NO_WARNINGS' \
	'-D_FX_CPU_=_FX_X64_'

# Flags passed to all source files.
CFLAGS_Release := \
	-Wall \
	-W \
	-Wno-missing-field-initializers \
	-Wno-sign-compare \
	-Wno-unused-parameter \
	-pthread \
	-fno-exceptions \
	-fPIC \
	-fPIC \
	-fno-strict-aliasing \
	-fdata-sections \
	-ffunction-sections \
	-O3 \
	-O2

# Flags passed to only C files.
CFLAGS_C_Release :=

# Flags passed to only C++ files.
CFLAGS_CC_Release := \
	-std=c++0x \
	-Wnon-virtual-dtor \
	-fno-rtti

INCS_Release := \
	-Ithird_party/freetype/include

DEFS_Release_x64 := \
	'-DOPJ_STATIC' \
	'-DV8_DEPRECATION_WARNINGS' \
	'-D_CRT_SECURE_NO_WARNINGS' \
	'-D_FX_CPU_=_FX_X64_'

# Flags passed to all source files.
CFLAGS_Release_x64 := \
	-Wall \
	-W \
	-Wno-missing-field-initializers \
	-Wno-sign-compare \
	-Wno-unused-parameter \
	-pthread \
	-fno-exceptions \
	-fPIC \
	-fPIC \
	-fno-strict-aliasing \
	-fdata-sections \
	-ffunction-sections \
	-O3 \
	-O2

# Flags passed to only C files.
CFLAGS_C_Release_x64 :=

# Flags passed to only C++ files.
CFLAGS_CC_Release_x64 := \
	-std=c++0x \
	-Wnon-virtual-dtor \
	-fno-rtti

INCS_Release_x64 := \
	-Ithird_party/freetype/include

OBJS := \
	$(obj).target/$(TARGET)/fpdfsdk/src/pdfwindow/PWL_Button.o \
	$(obj).target/$(TARGET)/fpdfsdk/src/pdfwindow/PWL_Caret.o \
	$(obj).target/$(TARGET)/fpdfsdk/src/pdfwindow/PWL_ComboBox.o \
	$(obj).target/$(TARGET)/fpdfsdk/src/pdfwindow/PWL_Edit.o \
	$(obj).target/$(TARGET)/fpdfsdk/src/pdfwindow/PWL_EditCtrl.o \
	$(obj).target/$(TARGET)/fpdfsdk/src/pdfwindow/PWL_FontMap.o \
	$(obj).target/$(TARGET)/fpdfsdk/src/pdfwindow/PWL_Icon.o \
	$(obj).target/$(TARGET)/fpdfsdk/src/pdfwindow/PWL_IconList.o \
	$(obj).target/$(TARGET)/fpdfsdk/src/pdfwindow/PWL_Label.o \
	$(obj).target/$(TARGET)/fpdfsdk/src/pdfwindow/PWL_ListBox.o \
	$(obj).target/$(TARGET)/fpdfsdk/src/pdfwindow/PWL_ListCtrl.o \
	$(obj).target/$(TARGET)/fpdfsdk/src/pdfwindow/PWL_Note.o \
	$(obj).target/$(TARGET)/fpdfsdk/src/pdfwindow/PWL_ScrollBar.o \
	$(obj).target/$(TARGET)/fpdfsdk/src/pdfwindow/PWL_Signature.o \
	$(obj).target/$(TARGET)/fpdfsdk/src/pdfwindow/PWL_SpecialButton.o \
	$(obj).target/$(TARGET)/fpdfsdk/src/pdfwindow/PWL_Utils.o \
	$(obj).target/$(TARGET)/fpdfsdk/src/pdfwindow/PWL_Wnd.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := \
	-pthread \
	-L$(builddir)

LDFLAGS_Debug_x64 := \
	-pthread \
	-L$(builddir)

LDFLAGS_Release := \
	-pthread \
	-L$(builddir)

LDFLAGS_Release_x64 := \
	-pthread \
	-L$(builddir)

LIBS :=

$(obj).target/libpdfwindow.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/libpdfwindow.a: LIBS := $(LIBS)
$(obj).target/libpdfwindow.a: TOOLSET := $(TOOLSET)
$(obj).target/libpdfwindow.a: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,alink_thin)

all_deps += $(obj).target/libpdfwindow.a
# Add target alias
.PHONY: pdfwindow
pdfwindow: $(obj).target/libpdfwindow.a

# Add target alias to "all" target.
.PHONY: all
all: pdfwindow

