xtiff.o:
		$(CC) $(PORT_INCLUDE) $(TIF_FLAGS) $(CFLAGS) $(GEOTIF_FLAGS) -c xtiff.c
		$(CC) $(PORT_INCLUDE) $(TIF_FLAGS) $(CFLAGS) $(GEOTIF_FLAGS) -c geo_free.c
		$(CC) $(PORT_INCLUDE) $(TIF_FLAGS) $(CFLAGS) $(GEOTIF_FLAGS) -c geo_get.c
		$(CC) $(PORT_INCLUDE) $(TIF_FLAGS) $(CFLAGS) $(GEOTIF_FLAGS) -c geo_names.c
		$(CC) $(PORT_INCLUDE) $(TIF_FLAGS) $(CFLAGS) $(GEOTIF_FLAGS) -c geo_new.c
		$(CC) $(PORT_INCLUDE) $(TIF_FLAGS) $(CFLAGS) $(GEOTIF_FLAGS) -c geo_print.c
		$(CC) $(PORT_INCLUDE) $(TIF_FLAGS) $(CFLAGS) $(GEOTIF_FLAGS) -c geo_set.c
		$(CC) $(PORT_INCLUDE) $(TIF_FLAGS) $(CFLAGS) $(GEOTIF_FLAGS) -c geo_tiffp.c
		$(CC) $(PORT_INCLUDE) $(TIF_FLAGS) $(CFLAGS) $(GEOTIF_FLAGS) -c geo_write.c
		$(CC) $(PORT_INCLUDE) $(TIF_FLAGS) $(CFLAGS) $(GEOTIF_FLAGS) -c geo_normalize.c
		$(CC) $(PORT_INCLUDE) $(TIF_FLAGS) $(CFLAGS) $(GEOTIF_FLAGS) -c geotiff_proj4.c
		$(CC) $(PORT_INCLUDE) $(TIF_FLAGS) $(CFLAGS) $(GEOTIF_FLAGS) -c geo_extra.c
		$(CC) $(PORT_INCLUDE) $(TIF_FLAGS) $(CFLAGS) $(GEOTIF_FLAGS) -c geo_trans.c
		$(CC) $(PORT_INCLUDE) $(TIF_FLAGS) $(CFLAGS) $(GEOTIF_FLAGS) -c geo_simpletags.c

clean:
	rm -f *.o