tif_aux.o:
		$(CC) $(PORT_INCLUDE) $(CFLAGS) $(TIF_FLAGS) $(GEOTIF_FLAGS) -c tif_aux.c 
		$(CC) $(CFLAGS) $(TIF_FLAGS) $(GEOTIF_FLAGS) $(PORT_INCLUDE) -c tif_close.c 
		$(CC) $(CFLAGS) $(TIF_FLAGS) $(GEOTIF_FLAGS) $(PORT_INCLUDE) -c tif_codec.c 
		$(CC) $(CFLAGS) $(TIF_FLAGS) $(GEOTIF_FLAGS) $(PORT_INCLUDE) -c tif_color.c 
		$(CC) $(CFLAGS) $(TIF_FLAGS) $(GEOTIF_FLAGS) $(PORT_INCLUDE) -c tif_compress.c 
		$(CC) $(CFLAGS) $(TIF_FLAGS) $(GEOTIF_FLAGS) $(PORT_INCLUDE) -c tif_dir.c 
		$(CC) $(CFLAGS) $(TIF_FLAGS) $(GEOTIF_FLAGS) $(PORT_INCLUDE) -c tif_dirinfo.c 
		$(CC) $(CFLAGS) $(TIF_FLAGS) $(GEOTIF_FLAGS) $(PORT_INCLUDE) -c tif_dirread.c 
		$(CC) $(CFLAGS) $(TIF_FLAGS) $(GEOTIF_FLAGS) $(PORT_INCLUDE) -c tif_dirwrite.c 
		$(CC) $(CFLAGS) $(TIF_FLAGS) $(GEOTIF_FLAGS) $(PORT_INCLUDE) -c tif_dumpmode.c 
		$(CC) $(CFLAGS) $(TIF_FLAGS) $(GEOTIF_FLAGS) $(PORT_INCLUDE) -c tif_error.c 
		$(CC) $(CFLAGS) $(TIF_FLAGS) $(GEOTIF_FLAGS) $(PORT_INCLUDE) -c tif_extension.c 
		$(CC) $(CFLAGS) $(TIF_FLAGS) $(GEOTIF_FLAGS) $(PORT_INCLUDE) -c tif_fax3.c 
		$(CC) $(CFLAGS) $(TIF_FLAGS) $(GEOTIF_FLAGS) $(PORT_INCLUDE) -c tif_fax3sm.c 
		$(CC) $(CFLAGS) $(TIF_FLAGS) $(GEOTIF_FLAGS) $(PORT_INCLUDE) -c tif_getimage.c 
		$(CC) $(CFLAGS) $(TIF_FLAGS) $(GEOTIF_FLAGS) $(PORT_INCLUDE) -c tif_jpeg.c 
		$(CC) $(CFLAGS) $(TIF_FLAGS) $(GEOTIF_FLAGS) $(PORT_INCLUDE) -c tif_jpeg_12.c 
		$(CC) $(CFLAGS) $(TIF_FLAGS) $(GEOTIF_FLAGS) $(PORT_INCLUDE) -c tif_flush.c 
		$(CC) $(CFLAGS) $(TIF_FLAGS) $(GEOTIF_FLAGS) $(PORT_INCLUDE) -c tif_luv.c 
		$(CC) $(CFLAGS) $(TIF_FLAGS) $(GEOTIF_FLAGS) $(PORT_INCLUDE) -c tif_lzw.c 
		$(CC) $(CFLAGS) $(TIF_FLAGS) $(GEOTIF_FLAGS) $(PORT_INCLUDE) -c tif_next.c 
		$(CC) $(CFLAGS) $(TIF_FLAGS) $(GEOTIF_FLAGS) $(PORT_INCLUDE) -c tif_ojpeg.c 
		$(CC) $(CFLAGS) $(TIF_FLAGS) $(GEOTIF_FLAGS) $(PORT_INCLUDE) -c tif_open.c 
		$(CC) $(CFLAGS) $(TIF_FLAGS) $(GEOTIF_FLAGS) $(PORT_INCLUDE) -c tif_packbits.c 
		$(CC) $(CFLAGS) $(TIF_FLAGS) $(GEOTIF_FLAGS) $(PORT_INCLUDE) -c tif_pixarlog.c 
		$(CC) $(CFLAGS) $(TIF_FLAGS) $(GEOTIF_FLAGS) $(PORT_INCLUDE) -c tif_predict.c 
		$(CC) $(CFLAGS) $(TIF_FLAGS) $(GEOTIF_FLAGS) $(PORT_INCLUDE) -c tif_print.c 
		$(CC) $(CFLAGS) $(TIF_FLAGS) $(GEOTIF_FLAGS) $(PORT_INCLUDE) -c tif_read.c 
		$(CC) $(CFLAGS) $(TIF_FLAGS) $(GEOTIF_FLAGS) $(PORT_INCLUDE) -c tif_swab.c 
		$(CC) $(CFLAGS) $(TIF_FLAGS) $(GEOTIF_FLAGS) $(PORT_INCLUDE) -c tif_strip.c 
		$(CC) $(CFLAGS) $(TIF_FLAGS) $(GEOTIF_FLAGS) $(PORT_INCLUDE) -c tif_thunder.c 
		$(CC) $(CFLAGS) $(TIF_FLAGS) $(GEOTIF_FLAGS) $(PORT_INCLUDE) -c tif_tile.c 
		$(CC) $(CFLAGS) $(TIF_FLAGS) $(GEOTIF_FLAGS) $(PORT_INCLUDE) -c tif_vsi.c 
		$(CC) $(CFLAGS) $(TIF_FLAGS) $(GEOTIF_FLAGS) $(PORT_INCLUDE) -c tif_version.c 
		$(CC) $(CFLAGS) $(TIF_FLAGS) $(GEOTIF_FLAGS) $(PORT_INCLUDE) -c tif_warning.c 
		$(CC) $(CFLAGS) $(TIF_FLAGS) $(GEOTIF_FLAGS) $(PORT_INCLUDE) -c tif_write.c 
		$(CC) $(CFLAGS) $(TIF_FLAGS) $(GEOTIF_FLAGS) $(PORT_INCLUDE) -c tif_zip.c 
		$(CC) $(CFLAGS) $(TIF_FLAGS) $(GEOTIF_FLAGS) $(PORT_INCLUDE) -c tif_lzma.c

clean:
	rm -f *.o