reader_digital_globe.o:
	$(CXX) $(CORE_INCLUDE) $(PORT_INCLUDE) $(OGR_INCLUDE) $(CXXFLAGS) -c reader_digital_globe.cpp
	$(CXX) $(CORE_INCLUDE) $(PORT_INCLUDE) $(OGR_INCLUDE) $(CXXFLAGS) -c reader_geo_eye.cpp
	$(CXX) $(CORE_INCLUDE) $(PORT_INCLUDE) $(OGR_INCLUDE) $(CXXFLAGS) -c reader_orb_view.cpp
	$(CXX) $(CORE_INCLUDE) $(PORT_INCLUDE) $(OGR_INCLUDE) $(CXXFLAGS) -c reader_pleiades.cpp
	$(CXX) $(CORE_INCLUDE) $(PORT_INCLUDE) $(OGR_INCLUDE) $(CXXFLAGS) -c reader_rdk1.cpp
	$(CXX) $(CORE_INCLUDE) $(PORT_INCLUDE) $(OGR_INCLUDE) $(CXXFLAGS) -c reader_landsat.cpp
	$(CXX) $(CORE_INCLUDE) $(PORT_INCLUDE) $(OGR_INCLUDE) $(CXXFLAGS) -c reader_spot.cpp
	$(CXX) $(CORE_INCLUDE) $(PORT_INCLUDE) $(OGR_INCLUDE) $(CXXFLAGS) -c reader_rapid_eye.cpp
	$(CXX) $(CORE_INCLUDE) $(PORT_INCLUDE) $(OGR_INCLUDE) $(CXXFLAGS) -c reader_alos.cpp
	$(CXX) $(CORE_INCLUDE) $(PORT_INCLUDE) $(OGR_INCLUDE) $(CXXFLAGS) -c reader_eros.cpp
	$(CXX) $(CORE_INCLUDE) $(PORT_INCLUDE) $(OGR_INCLUDE) $(CXXFLAGS) -c reader_kompsat.cpp

clean:
	rm -f *.o