#!/bin/bash
echo 'LOCAL_PATH := $(call my-dir)' 
export TP=$1
export TG=$2
echo 'include $(CLEAR_VARS)'
echo 'LOCAL_MODULE := gdal'
echo 'LOCAL_SRC_FILES := '$TP'/'$TG'/lib/libgdal.a'
echo 'LOCAL_EXPORT_LDLIBS := -lz'
echo 'include $(PREBUILT_STATIC_LIBRARY)'

echo 'include $(CLEAR_VARS)'
echo 'LOCAL_MODULE := sqlite'
echo 'LOCAL_SRC_FILES := '$TP'/'$TG'/lib/libsqlite3.a'
echo 'LOCAL_EXPORT_LDLIBS := -lz'
echo 'include $(PREBUILT_STATIC_LIBRARY)'

echo 'include $(CLEAR_VARS)'
echo 'LOCAL_MODULE := proj4'
echo 'LOCAL_SRC_FILES := '$TP'/'$TG'/lib/libproj.a' 
echo 'LOCAL_EXPORT_LDLIBS := -lz'
echo 'include $(PREBUILT_STATIC_LIBRARY)'

echo 'nclude $(CLEAR_VARS)'
echo 'LOCAL_MODULE := fxcrt'
echo 'LOCAL_SRC_FILES := '$TP'/'$TG'/pdfium/install/lib/pdfium/libfxcrt.a'
LOCAL_EXPORT_LDLIBS := -lz
include $(PREBUILT_STATIC_LIBRARY)

echo 'include $(CLEAR_VARS)'
echo 'LOCAL_MODULE := fxedit'
echo 'LOCAL_SRC_FILES := '$TP'/'$TG'/pdfium/install/lib/pdfium/libfxedit.a'
echo 'LOCAL_EXPORT_LDLIBS := -lz'
echo 'include $(PREBUILT_STATIC_LIBRARY)'

echo 'include $(CLEAR_VARS)'
echo 'LOCAL_MODULE := fxge'
echo 'LOCAL_SRC_FILES := '$TP'/'$TG'/pdfium/install/lib/pdfium/libfxge.a'
echo 'LOCAL_EXPORT_LDLIBS := -lz'
echo 'include $(PREBUILT_STATIC_LIBRARY)'

echo 'include $(CLEAR_VARS)'
echo 'LOCAL_MODULE := pdfwindow'
echo 'LOCAL_SRC_FILES := '$TP'/'$TG'/pdfium/install/lib/pdfium/libpdfwindow.a' 
echo 'LOCAL_EXPORT_LDLIBS := -lz'
echo 'include $(PREBUILT_STATIC_LIBRARY)'

echo 'include $(CLEAR_VARS)'
echo 'LOCAL_MODULE := fdrm'
echo 'LOCAL_SRC_FILES :='$TP'/'$TG'/pdfium/install/lib/pdfium/libfdrm.a '
echo 'LOCAL_EXPORT_LDLIBS := -lz'
echo 'include $(PREBUILT_STATIC_LIBRARY)'

echo 'include $(CLEAR_VARS)'
echo 'LOCAL_MODULE := fpdfdoc'
echo 'LOCAL_SRC_FILES := '$TP'/'$TG'/pdfium/install/lib/pdfium/libfpdfdoc.a'
echo 'LOCAL_EXPORT_LDLIBS := -lz'
echo 'include $(PREBUILT_STATIC_LIBRARY)'

echo 'include $(CLEAR_VARS)'
echo 'LOCAL_MODULE := fpdfapi'
echo 'LOCAL_SRC_FILES := '$TP'/'$TG'/pdfium/install/lib/pdfium/libfpdfapi.a' 
echo 'LOCAL_EXPORT_LDLIBS := -lz'
echo 'include $(PREBUILT_STATIC_LIBRARY)'

echo 'include $(CLEAR_VARS)'
echo 'LOCAL_MODULE := fpdftext'
echo 'LOCAL_SRC_FILES := '$TP'/'$TG'/pdfium/install/lib/pdfium/libfpdftext.a' 
echo 'LOCAL_EXPORT_LDLIBS := -lz'
echo 'include $(PREBUILT_STATIC_LIBRARY)'

echo 'include $(CLEAR_VARS)'
echo 'LOCAL_MODULE := formfiller'
echo 'LOCAL_SRC_FILES := '$TP'/'$TG'/pdfium/install/lib/pdfium/libformfiller.a' 
echo 'LOCAL_EXPORT_LDLIBS := -lz'
echo 'include $(PREBUILT_STATIC_LIBRARY)'

echo 'include $(CLEAR_VARS)'
echo 'LOCAL_MODULE := fxcodec'
echo 'LOCAL_SRC_FILES := '$TP'/'$TG'/pdfium/install/lib/pdfium/libfxcodec.a' 
echo 'LOCAL_EXPORT_LDLIBS := -lz'
echo 'include $(PREBUILT_STATIC_LIBRARY)'
echo ''
echo 'include $(CLEAR_VARS)'
echo 'LOCAL_MODULE := freetype'
echo 'LOCAL_SRC_FILES := '$TP'/'$TG'/pdfium/install/lib/pdfium/libfreetype.a' 
echo 'LOCAL_EXPORT_LDLIBS := -lz'
echo 'include $(PREBUILT_STATIC_LIBRARY)'

echo 'include $(CLEAR_VARS)'
echo 'LOCAL_MODULE := bigint'
echo 'LOCAL_SRC_FILES := '$TP'/'$TG'/pdfium/install/lib/pdfium/libbigint.a' 
echo 'LOCAL_EXPORT_LDLIBS := -lz'
echo 'include $(PREBUILT_STATIC_LIBRARY)'

echo 'include $(CLEAR_VARS)'
echo 'LOCAL_MODULE := pdfium'
echo 'LOCAL_SRC_FILES := '$TP'/'$TG'/pdfium/install/lib/pdfium/libpdfium.a'
echo 'LOCAL_EXPORT_LDLIBS := -lz'
echo 'include $(PREBUILT_STATIC_LIBRARY)'

echo 'include $(CLEAR_VARS)'
echo 'LOCAL_MODULE := fx_libopenjpeg'
echo 'LOCAL_SRC_FILES := '$TP'/'$TG'/pdfium/install/lib/pdfium/libfx_libopenjpeg.a'
echo 'LOCAL_EXPORT_LDLIBS := -lz'
echo 'include $(PREBUILT_STATIC_LIBRARY)'

echo 'include $(CLEAR_VARS)'
echo 'LOCAL_MODULE := fx_lcms2'
echo 'LOCAL_SRC_FILES := '$TP'/'$TG'/pdfium/install/lib/pdfium/libfx_lcms2.a'
echo 'LOCAL_EXPORT_LDLIBS := -lz'
echo 'include $(PREBUILT_STATIC_LIBRARY)'

echo 'include $(CLEAR_VARS)'
echo 'LOCAL_MODULE := fx_libjpeg'
echo 'LOCAL_SRC_FILES := '$TP'/'$TG'/pdfium/install/lib/pdfium/libfx_libjpeg.a'
echo 'LOCAL_EXPORT_LDLIBS := -lz'
echo 'include $(PREBUILT_STATIC_LIBRARY)'

echo 'include $(CLEAR_VARS)'
echo 'LOCAL_MODULE := fx_agg'
echo 'LOCAL_SRC_FILES := '$TP'/'$TG'/pdfium/install/lib/pdfium/libfx_agg.a'
echo 'LOCAL_EXPORT_LDLIBS := -lz'
echo 'include $(PREBUILT_STATIC_LIBRARY)'

echo 'include $(CLEAR_VARS)'
echo 'LOCAL_MODULE := fx_zlib'
echo 'LOCAL_SRC_FILES := '$TP'/'$TG'/pdfium/install/lib/pdfium/libfx_zlib.a'
echo 'LOCAL_EXPORT_LDLIBS := -lz'
echo 'include $(PREBUILT_STATIC_LIBRARY)'

echo 'include $(CLEAR_VARS)'
echo 'LOCAL_MODULE := shgdal'
echo 'LOCAL_SRC_FILES := '$TP'/'$TG'/lib/libgdal210.so'
echo 'LOCAL_EXPORT_LDLIBS := -lz'
echo 'include $(PREBUILT_SHARED_LIBRARY)'

echo 'include $(CLEAR_VARS)'
echo 'LOCAL_MODULE := geopdfreader'
echo 'LOCAL_SRC_FILES := gdal_to_tiles.cpp gdalwarp_bin.cpp global_mercator.cpp logger.cpp logger2.cpp main.cpp utils.cpp GeoPDFReader.cpp com_terragoedge_geopdf_read_GeoPDFReader.cpp '
echo 'LOCAL_SRC_FILES := '$TP'/'$TG'/include  $(LOCAL_PATH)/png'
echo 'LOCAL_STATIC_LIBRARIES := gdal sqlite proj4 fpdfapi fpdfdoc pdfium  fpdftext formfiller pdfwindow fxedit  fxcodec fx_libopenjpeg fx_lcms2 fx_libjpeg fx_zlib fdrm fxge freetype fx_agg fxcrt bigint'
echo 'LOCAL_SHARED_LIBRARIES := shgdal'
echo 'include $(BUILD_SHARED_LIBRARY)'
