rawdataset.o:
	$(CXX) $(OGR_INCLUDE) $(CORE_INCLUDE) $(PORT_INCLUDE) $(CXXFLAGS) -c rawdataset.cpp
	$(CXX) $(OGR_INCLUDE) $(CORE_INCLUDE) $(PORT_INCLUDE) $(CXXFLAGS) -c ehdrdataset.cpp
	$(CXX) $(OGR_INCLUDE) $(CORE_INCLUDE) $(PORT_INCLUDE) $(CXXFLAGS) -c pauxdataset.cpp
	$(CXX) $(OGR_INCLUDE) $(CORE_INCLUDE) $(PORT_INCLUDE) $(CXXFLAGS) -c doq1dataset.cpp
	$(CXX) $(OGR_INCLUDE) $(CORE_INCLUDE) $(PORT_INCLUDE) $(CXXFLAGS) -c doq2dataset.cpp
	$(CXX) $(OGR_INCLUDE) $(CORE_INCLUDE) $(PORT_INCLUDE) $(CXXFLAGS) -c mffdataset.cpp
	$(CXX) $(OGR_INCLUDE) $(CORE_INCLUDE) $(PORT_INCLUDE) $(CXXFLAGS) -c hkvdataset.cpp
	$(CXX) $(OGR_INCLUDE) $(CORE_INCLUDE) $(PORT_INCLUDE) $(CXXFLAGS) -c pnmdataset.cpp
	$(CXX) $(OGR_INCLUDE) $(CORE_INCLUDE) $(PORT_INCLUDE) $(CXXFLAGS) -c fujibasdataset.cpp
	$(CXX) $(OGR_INCLUDE) $(CORE_INCLUDE) $(PORT_INCLUDE) $(CXXFLAGS) -c envidataset.cpp
	$(CXX) $(OGR_INCLUDE) $(CORE_INCLUDE) $(PORT_INCLUDE) $(CXXFLAGS) -c gscdataset.cpp
	$(CXX) $(OGR_INCLUDE) $(CORE_INCLUDE) $(PORT_INCLUDE) $(CXXFLAGS) -c fastdataset.cpp
	$(CXX) $(OGR_INCLUDE) $(CORE_INCLUDE) $(PORT_INCLUDE) $(CXXFLAGS) -c atlsci_spheroid.cpp
	$(CXX) $(OGR_INCLUDE) $(CORE_INCLUDE) $(PORT_INCLUDE) $(CXXFLAGS) -c btdataset.cpp
	$(CXX) $(OGR_INCLUDE) $(CORE_INCLUDE) $(PORT_INCLUDE) $(CXXFLAGS) -c landataset.cpp
	$(CXX) $(OGR_INCLUDE) $(CORE_INCLUDE) $(PORT_INCLUDE) $(CXXFLAGS) -c cpgdataset.cpp
	$(CXX) $(OGR_INCLUDE) $(CORE_INCLUDE) $(PORT_INCLUDE) $(CXXFLAGS) -c idadataset.cpp
	$(CXX) $(OGR_INCLUDE) $(CORE_INCLUDE) $(PORT_INCLUDE) $(CXXFLAGS) -c ndfdataset.cpp
	$(CXX) $(OGR_INCLUDE) $(CORE_INCLUDE) $(PORT_INCLUDE) $(CXXFLAGS) -c dipxdataset.cpp
	$(CXX) $(OGR_INCLUDE) $(CORE_INCLUDE) $(PORT_INCLUDE) $(CXXFLAGS) -c genbindataset.cpp
	$(CXX) $(OGR_INCLUDE) $(CORE_INCLUDE) $(PORT_INCLUDE) $(CXXFLAGS) -c lcpdataset.cpp
	$(CXX) $(OGR_INCLUDE) $(CORE_INCLUDE) $(PORT_INCLUDE) $(CXXFLAGS) -c eirdataset.cpp
	$(CXX) $(OGR_INCLUDE) $(CORE_INCLUDE) $(PORT_INCLUDE) $(CXXFLAGS) -c gtxdataset.cpp
	$(CXX) $(OGR_INCLUDE) $(CORE_INCLUDE) $(PORT_INCLUDE) $(CXXFLAGS) -c loslasdataset.cpp
	$(CXX) $(OGR_INCLUDE) $(CORE_INCLUDE) $(PORT_INCLUDE) $(CXXFLAGS) -c ntv2dataset.cpp
	$(CXX) $(OGR_INCLUDE) $(CORE_INCLUDE) $(PORT_INCLUDE) $(CXXFLAGS) -c ace2dataset.cpp
	$(CXX) $(OGR_INCLUDE) $(CORE_INCLUDE) $(PORT_INCLUDE) $(CXXFLAGS) -c snodasdataset.cpp
	$(CXX) $(OGR_INCLUDE) $(CORE_INCLUDE) $(PORT_INCLUDE) $(CXXFLAGS) -c ctable2dataset.cpp
	$(CXX) $(OGR_INCLUDE) $(CORE_INCLUDE) $(PORT_INCLUDE) $(CXXFLAGS) -c krodataset.cpp
	$(CXX) $(OGR_INCLUDE) $(CORE_INCLUDE) $(PORT_INCLUDE) $(CXXFLAGS) -c roipacdataset.cpp
	$(CXX) $(OGR_INCLUDE) $(CORE_INCLUDE) $(PORT_INCLUDE) $(CXXFLAGS) -c iscedataset.cpp

clean:
	rm -f *.o